[workspace]
resolver="2"
members = [
    "vault-tasks-core",
]


[workspace.package]
edition = "2021"
repository = "https://github.com/louis-thevenet/vault-tasks-core"
authors = ["Louis Thevenet <louis.tvnt@gmail.com>"]
license = "MIT"
