[package]
name = "vault-tasks-time-management"
version = "0.3.0"
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
description = "Pomodoro & FlowTime time managment techniques"

[dependencies]
anyhow = "1.0.93"
color-eyre = "0.6.3"
